name: hinatazaka_song_record_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^2.2.0
  shared_preferences: ^2.2.1

dev_dependencies:
  build_runner: ^2.3.2
  custom_lint: ^0.5.3
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  supabase_flutter: ^1.10.21

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: '#FFF422'
  adaptive_icon_foreground: "assets/icon/icon.png"